import { Property } from "./types/property";

// Mexican real estate data
export const COLONIAS = [
  "Roma Norte, CDMX", "Condesa, CDMX", "Polanco, CDMX", "Del Valle, CDMX", "Coyoacán, CDMX",
  "Providencia, GDL", "Chapalita, GDL", "Americana, GDL", "Lomas del Valle, GDL",
  "San Pedro Garza Garza García, MTY", "Valle Oriente, MTY", "Del Valle, MTY",
  "Cancún Zona Hotelera, QR", "Playa del Carmen Centro, QR", "Tulum Centro, QR",
  "Puerto Vallarta Centro, JAL", "San Miguel de Allende Centro, GTO"
];

export const PROPERTIES: Property[] = [
  {
    id: "rmn-214",
    title: "Casa en Roma Norte",
    type: "Casa",
    operation: "venta",
    price: 8950000,
    location: "Roma Norte, Cuauhtémoc, CDMX",
    city: "CDMX",
    colonia: "Roma Norte",
    beds: 3, baths: 2.5, m2: 185, parking: 2,
    year: 2019,
    featured: true,
    tag: "Nuevo",
    desc: "Casa de autor sobre Av. Álvaro Obregón. Acabados en concreto pulido, herrería negra y maderas cálidas. Doble altura en sala, jardín interior.",
    specs: [
      ["Superficie construida", "185 m²"],
      ["Terreno", "220 m²"],
      ["Recámaras", "3"],
      ["Baños", "2.5"],
      ["Estacionamiento", "2 autos"],
      ["Antigüedad", "7 años"],
      ["Mantenimiento", "$2,800 / mes"]
    ],
    amenities: ["Roof garden", "Estudio", "Closet vestidor", "Cocina integral", "Calentador solar", "Seguridad 24/7"],
    agent: { name: "Mariana Cárdenas", role: "Agente certificada AMPI", rating: 4.9, reviews: 87, initials: "MC" },
    palette: ["#C4572E", "#E8C28C", "#1A1A1A", "#F2EFE6"],
    accent: "#C4572E"
  },
  {
    id: "pol-089",
    title: "PH en Polanco",
    type: "Departamento",
    operation: "venta",
    price: 23500000,
    location: "Polanco IV Sección, Miguel Hidalgo, CDMX",
    city: "CDMX",
    colonia: "Polanco",
    beds: 4, baths: 4, m2: 340, parking: 3,
    year: 2022,
    featured: true,
    tag: "Penthouse",
    desc: "Penthouse de dos niveles con terraza privada. Vista panorámica al Bosque de Chapultepec. Acabados europeos, domótica integrada.",
    specs: [["Superficie", "340 m²"], ["Terraza", "120 m²"], ["Recámaras", "4"], ["Baños", "4"], ["Estacionamiento", "3"], ["Mantenimiento", "$18,500 / mes"]],
    amenities: ["Terraza con jacuzzi", "Gimnasio", "Alberca", "Concierge", "Valet parking", "Pet friendly"],
    agent: { name: "Alejandro Ruiz", role: "Broker · Polanco Properties", rating: 5.0, reviews: 132, initials: "AR" },
    palette: ["#1A1A1A", "#C4572E", "#E8E6DE"],
    accent: "#1A1A1A"
  },
  {
    id: "cnd-442",
    title: "Depa en Condesa",
    type: "Departamento",
    operation: "renta",
    price: 38500,
    location: "Hipódromo Condesa, Cuauhtémoc, CDMX",
    city: "CDMX",
    colonia: "Condesa",
    beds: 2, baths: 2, m2: 95, parking: 1,
    year: 1948,
    tag: "Art Déco",
    desc: "Departamento en edificio art déco restaurado frente a Parque México. Pisos originales de parquet, techos altos.",
    specs: [["Superficie", "95 m²"], ["Recámaras", "2"], ["Baños", "2"], ["Estacionamiento", "1"], ["Mantenimiento", "Incluido"]],
    amenities: ["Amueblado", "Internet", "Balcón", "Vista al parque", "Pet friendly", "Bodega"],
    agent: { name: "Renata Solís", role: "Agente independiente", rating: 4.8, reviews: 54, initials: "RS" },
    palette: ["#E8C28C", "#8C6A42", "#F2EFE6"],
    accent: "#8C6A42"
  },
  {
    id: "tlm-019",
    title: "Villa en Tulum",
    type: "Casa",
    operation: "venta",
    price: 14200000,
    location: "Aldea Zamá, Tulum, Quintana Roo",
    city: "Tulum",
    colonia: "Aldea Zamá",
    beds: 3, baths: 3.5, m2: 280, parking: 2,
    year: 2024,
    featured: true,
    tag: "Pre-venta",
    desc: "Villa de diseño orgánico en la selva. Alberca privada, rooftop con vista al mar. Materiales locales: chukum, madera tzalam.",
    specs: [["Construcción", "280 m²"], ["Terreno", "450 m²"], ["Recámaras", "3"], ["Baños", "3.5"], ["Alberca", "28 m²"], ["Entrega", "Oct 2026"]],
    amenities: ["Alberca privada", "Rooftop", "Cenote comunal", "Seguridad", "Gimnasio", "Yoga shala"],
    agent: { name: "Daniela Mendoza", role: "Playa & Jungla Realty", rating: 4.9, reviews: 43, initials: "DM" },
    palette: ["#8AA89A", "#C4572E", "#F2EFE6"],
    accent: "#8AA89A"
  },
  {
    id: "mty-721",
    title: "Depto San Pedro Garza",
    type: "Departamento",
    operation: "venta",
    price: 12800000,
    location: "Valle de San Ángel, San Pedro Garza García, NL",
    city: "Monterrey",
    colonia: "San Pedro",
    beds: 3, baths: 3, m2: 210, parking: 2,
    year: 2023,
    tag: "Estreno",
    desc: "Departamento moderno con vista al Cerro de la Silla. Torre con amenidades premium, cerca de Calzada del Valle.",
    specs: [["Superficie", "210 m²"], ["Recámaras", "3"], ["Baños", "3"], ["Estacionamiento", "2"], ["Bodega", "Sí"]],
    amenities: ["Alberca", "Gimnasio", "Sky lounge", "Business center", "Asadores", "Pet park"],
    agent: { name: "Carlos Treviño", role: "MTY Premium Homes", rating: 4.7, reviews: 91, initials: "CT" },
    palette: ["#3A4454", "#C4572E", "#E8E6DE"],
    accent: "#3A4454"
  },
  {
    id: "gdl-310",
    title: "Casa en Providencia",
    type: "Casa",
    operation: "venta",
    price: 6750000,
    location: "Providencia 1a Sección, Guadalajara, JAL",
    city: "GDL",
    colonia: "Providencia",
    beds: 4, baths: 3, m2: 240, parking: 2,
    year: 1978,
    tag: "Remodelada",
    desc: "Casa de los 70s totalmente remodelada. Jardín con árboles maduros, estudio independiente, cochera techada.",
    specs: [["Construcción", "240 m²"], ["Terreno", "320 m²"], ["Recámaras", "4"], ["Baños", "3"], ["Antigüedad", "Remodelada 2023"]],
    amenities: ["Jardín", "Estudio", "Terraza", "Calentador solar", "Cisterna", "Cuarto servicio"],
    agent: { name: "Fernanda López", role: "GDL Realty Collective", rating: 4.9, reviews: 108, initials: "FL" },
    palette: ["#E8C28C", "#8C6A42", "#F2EFE6"],
    accent: "#8C6A42"
  },
  {
    id: "cnd-911",
    title: "Loft Amueblado Condesa",
    type: "Departamento",
    operation: "renta",
    price: 28000,
    location: "Condesa, Cuauhtémoc, CDMX",
    city: "CDMX",
    colonia: "Condesa",
    beds: 1, baths: 1, m2: 62, parking: 1,
    year: 2020,
    tag: "Amueblado",
    desc: "Loft contemporáneo con doble altura. A una cuadra de Parque España. Ideal para nómada digital.",
    specs: [["Superficie", "62 m²"], ["Recámaras", "1"], ["Baños", "1"], ["Contrato", "Mínimo 6 meses"]],
    amenities: ["Amueblado", "Internet 300mb", "Servicios incluidos", "Lavadora/secadora", "Roof común"],
    agent: { name: "Paola Jiménez", role: "Casa Condesa Rentas", rating: 4.8, reviews: 67, initials: "PJ" },
    palette: ["#1A1A1A", "#C4572E", "#F2EFE6"],
    accent: "#1A1A1A"
  },
  {
    id: "smr-202",
    title: "Casa Colonial San Miguel",
    type: "Casa",
    operation: "venta",
    price: 11500000,
    location: "Centro Histórico, San Miguel de Allende, GTO",
    city: "San Miguel",
    colonia: "Centro",
    beds: 4, baths: 4, m2: 310, parking: 2,
    year: 1890,
    featured: true,
    tag: "Histórica",
    desc: "Casona colonial del siglo XIX con patio central. Remodelada con estándar boutique. Tres cuadras del Jardín.",
    specs: [["Construcción", "310 m²"], ["Terreno", "380 m²"], ["Recámaras", "4"], ["Baños", "4"], ["Patio central", "Sí"]],
    amenities: ["Patio colonial", "Chimenea", "Roof con cúpula", "Bóvedas catalanas", "Pozo", "Cuarto servicio"],
    agent: { name: "Santiago Pérez", role: "SMA Homes Boutique", rating: 5.0, reviews: 76, initials: "SP" },
    palette: ["#C4572E", "#E8C28C", "#1A1A1A"],
    accent: "#C4572E"
  },
  {
    id: "pch-055",
    title: "Penthouse Playa",
    type: "Departamento",
    operation: "renta",
    price: 45000,
    location: "Playa del Carmen Centro, QR",
    city: "Playa",
    colonia: "5a Avenida",
    beds: 2, baths: 2, m2: 140, parking: 1,
    year: 2021,
    tag: "Vacacional",
    desc: "Penthouse frente al mar. Terraza con alberca privada, vista al Caribe. Ideal renta vacacional o residencia.",
    specs: [["Superficie", "140 m²"], ["Terraza", "80 m²"], ["Recámaras", "2"], ["Baños", "2"]],
    amenities: ["Vista al mar", "Alberca privada", "Gimnasio", "Concierge", "Playa privada"],
    agent: { name: "Isabela Torres", role: "Caribe Homes", rating: 4.9, reviews: 95, initials: "IT" },
    palette: ["#8AA89A", "#E8C28C", "#F2EFE6"],
    accent: "#8AA89A"
  },
  {
    id: "dvl-312",
    title: "Casa Del Valle",
    type: "Casa",
    operation: "venta",
    price: 7200000,
    location: "Del Valle Centro, Benito Juárez, CDMX",
    city: "CDMX",
    colonia: "Del Valle",
    beds: 3, baths: 2, m2: 165, parking: 2,
    year: 1985,
    tag: "Oportunidad",
    desc: "Casa de dos niveles en calle tranquila. Para remodelar o vivir tal cual. Excelente ubicación, cerca de Parque Hundido.",
    specs: [["Construcción", "165 m²"], ["Terreno", "180 m²"], ["Recámaras", "3"], ["Baños", "2"]],
    amenities: ["Jardín", "Cuarto servicio", "Calentador gas", "Cisterna"],
    agent: { name: "Mariana Cárdenas", role: "Agente certificada AMPI", rating: 4.9, reviews: 87, initials: "MC" },
    palette: ["#3A4454", "#E8C28C", "#F2EFE6"],
    accent: "#3A4454"
  },
  {
    id: "coy-487",
    title: "Casa en Coyoacán",
    type: "Casa",
    operation: "venta",
    price: 9800000,
    location: "Del Carmen Coyoacán, CDMX",
    city: "CDMX",
    colonia: "Coyoacán",
    beds: 4, baths: 3, m2: 260, parking: 2,
    year: 1960,
    tag: "Barrio mágico",
    desc: "Casa en calle empedrada a 4 cuadras del Jardín Centenario. Jardín con buganvilia, patio interior.",
    specs: [["Construcción", "260 m²"], ["Terreno", "340 m²"], ["Recámaras", "4"], ["Baños", "3"]],
    amenities: ["Jardín grande", "Patio", "Estudio", "Chimenea", "Cuarto servicio", "Bodega"],
    agent: { name: "Luis Paredes", role: "Sur CDMX Realty", rating: 4.8, reviews: 63, initials: "LP" },
    palette: ["#C4572E", "#8AA89A", "#F2EFE6"],
    accent: "#C4572E"
  },
  {
    id: "trn-009",
    title: "Terreno Valle de Bravo",
    type: "Terreno",
    operation: "venta",
    price: 4500000,
    location: "Avándaro, Valle de Bravo, EDOMEX",
    city: "Valle de Bravo",
    colonia: "Avándaro",
    beds: 0, baths: 0, m2: 1200, parking: 0,
    year: null,
    tag: "Terreno",
    desc: "Terreno en fraccionamiento con club de golf. Vista al lago, rodeado de pinos. Listo para construir.",
    specs: [["Terreno", "1,200 m²"], ["Frente", "24 m"], ["Fondo", "50 m"], ["Uso de suelo", "Habitacional"]],
    amenities: ["Vista al lago", "Pinos maduros", "Servicios", "Club de golf", "Seguridad"],
    agent: { name: "Patricia Aguilar", role: "Valle de Bravo Properties", rating: 4.9, reviews: 41, initials: "PA" },
    palette: ["#8AA89A", "#8C6A42", "#F2EFE6"],
    accent: "#8AA89A"
  }
];

export const CITIES = [
  { name: "Ciudad de México", short: "CDMX", count: 4821, hot: true },
  { name: "Guadalajara", short: "GDL", count: 2108 },
  { name: "Monterrey", short: "MTY", count: 1743 },
  { name: "Querétaro", short: "QRO", count: 892 },
  { name: "Mérida", short: "MID", count: 1124, hot: true },
  { name: "Puebla", short: "PUE", count: 654 },
  { name: "Tulum", short: "TUM", count: 421, hot: true },
  { name: "Playa del Carmen", short: "PLY", count: 587 },
  { name: "San Miguel Allende", short: "SMA", count: 318 },
  { name: "Puerto Vallarta", short: "PVR", count: 465 }
];

export const PROPERTY_TYPES = [
  { id: "casa", name: "Casa", icon: "house" },
  { id: "depa", name: "Departamento", icon: "apartment" },
  { id: "terreno", name: "Terreno", icon: "land" },
  { id: "local", name: "Local", icon: "shop" },
  { id: "oficina", name: "Oficina", icon: "office" },
  { id: "bodega", name: "Bodega", icon: "warehouse" }
];

// Format MXN currency
export function fmtMXN(n: number, short = false) {
  if (short && n >= 1000000) {
    return "$" + (n/1000000).toFixed(n % 1000000 === 0 ? 0 : 1) + " M";
  }
  return "$" + n.toLocaleString("es-MX");
}
